@baseUrl = {{HostAddress}}

### AUTH ENDPOINTS

### Login as Super Admin
# @name loginSuperAdmin
POST {{baseUrl}}/api/auth/login 
Content-Type: application/json

{
  "UserName": "{{SuperAdminName}}",
  "Password": "{{SuperAdminPassword}}"
}

### Refresh Login
# @name loginSuperAdmin
POST {{baseUrl}}/api/auth/refresh-login 
Content-Type: application/json

{
  "AccessToken": "{{loginSuperAdmin.response.body.$.accessToken}}",
  "RefreshToken": "{{loginSuperAdmin.response.body.$.refreshToken}}"
}


### User ENDPOINTS

### Get Me
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Change profile picture
PATCH {{baseUrl}}/api/users/change-picture
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="NewProfilePictureFile"; filename="profile-2.jpg"
Content-Type: image/jpeg

< ../images/profile-pictures/profile-2.jpg
--boundary--

### Skill ENDPOINTS

### Get skills
GET {{baseUrl}}/api/skills
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Get skill by id
GET {{baseUrl}}/api/skills/436bc62d-dd9a-40ae-2fcf-08dd5d5fb3c8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Create a new skill
POST {{baseUrl}}/api/skills
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: application/json

{
 "Name": "Backend",
 "Description": "I love C#",
 "ProficiencyLevel": "Advanced",
 "YearsOfExperience": "3"
}

### Update a skill
PATCH {{baseUrl}}/api/skills/436bc62d-dd9a-40ae-2fcf-08dd5d5fb3c8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: application/json

{
 "Name": "Programming",
 "Description": "I love C#",
 "ProficiencyLevel": "Advanced",
 "YearsOfExperience": "7"
}

### Delete a skill by Id
DELETE {{baseUrl}}/api/skills/436bc62d-dd9a-40ae-2fcf-08dd5d5fb3c8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### ACHIEVEMENT ENDPOINTS

### Get all achievements
GET {{baseUrl}}/api/achievements
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Get achievement by ID
GET {{baseUrl}}/api/achievements/44efa669-e446-4468-2349-08dd5d5fdce3
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Create a new achievement
POST {{baseUrl}}/api/achievements
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: application/json

{
  "Title": "Completed AI Project",
  "Description": "Successfully built and deployed an AI model.",
  "AchievedAt": "2024-02-25T00:00:00Z"
}

### Update an achievement
PATCH {{baseUrl}}/api/achievements/44efa669-e446-4468-2349-08dd5d5fdce3
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: application/json

{
  "Title": "Completed Advanced AI Project",
  "Description": "Enhanced AI model with better accuracy.",
  "AchievedAt": "2024-03-10T00:00:00Z"
}

### Delete an achievement by ID
DELETE {{baseUrl}}/api/achievements/44efa669-e446-4468-2349-08dd5d5fdce3
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### PROJECT ENDPOINTS

### Get all projects
GET {{baseUrl}}/api/projects
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Get a project by Id
GET {{baseUrl}}/api/projects/07031f32-20d7-4b57-d8f9-08dd5d5ff7d8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Create a new project
POST {{baseUrl}}/api/projects
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="Name"

Project 1
--boundary
Content-Disposition: form-data; name="Description"

Project 1 description goes here.
--boundary
Content-Disposition: form-data; name="RepoUrl"

https://github.com/username/my-repo
--boundary
Content-Disposition: form-data; name="LiveUrl"

https://my-project-live-url
--boundary
Content-Disposition: form-data; name="ProjectCoverImageFile"; filename="project-cover-1.jpg"
Content-Type: image/jpeg

< ../images/cover-images/project-cover-1.jpg
--boundary--

### Update a project by
PATCH {{baseUrl}}/api/projects/07031f32-20d7-4b57-d8f9-08dd5d5ff7d8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="Name"

Updated Project Name
--boundary
Content-Disposition: form-data; name="Description"

Updated description.
--boundary
Content-Disposition: form-data; name="RepoUrl"

https://github.com/username/updated-repo
--boundary
Content-Disposition: form-data; name="LiveUrl"

https://updated-project-live-url
--boundary
Content-Disposition: form-data; name="ProjectCoverImageFile"; filename="project-cover-2.jpg"
Content-Type: image/jpeg

< ../images/cover-images/project-cover-2.jpg
--boundary--

### Delete a project by Id
DELETE {{baseUrl}}/api/projects/07031f32-20d7-4b57-d8f9-08dd5d5ff7d8
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### CONTACT ENDPOINTS
### Get all contacts
GET {{baseUrl}}/api/contacts
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Get a contact by Id
GET {{baseUrl}}/api/contacts/baed26dc-9bc7-40e9-87f7-08dd5d623a0b
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}

### Create a new contact
POST {{baseUrl}}/api/contacts
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "kahop73259@egvoo.com",
  "Message": "Hello, would like to get your services!",
  "Subject": "job_opportunity"
}

### Answer a contact
PATCH {{baseUrl}}/api/contacts/5abaf5f0-d045-4f33-7040-08dd5d6cafd1/answer
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
Content-Type: application/json

{
  "Message": "Yes, would love to work together!"
}

### Delete a contact by Id
DELETE {{baseUrl}}/api/contacts/5abaf5f0-d045-4f33-7040-08dd5d6cafd1
Authorization: Bearer {{loginSuperAdmin.response.body.$.accessToken}}
